const ENABLE_SELECT_WAY_BUTTONS = "ENABLE_SELECT_WAY_BUTTONS";
const START_DATA_FETCHING = 'START_DATA_FETCHING';
const DISPLAY_CONNECTION = 'DISPLAY_CONNECTION';
export {
  ENABLE_SELECT_WAY_BUTTONS,
  START_DATA_FETCHING,
  DISPLAY_CONNECTION
};
